### ISSUE TITLE
Xamarin Forms UWP MainPage Change Throws Exception

### ISSUE THREAD

**Issue by MattRames** [azchohfi/LottieUWP#29]
When changing the MainPage of the app while an animation view is on screen an InvalidOperationException is thrown.  Details below.

Cannot assign a native control without an Element; Renderer unbound and/or disposed. Please consult Xamarin.Forms renderers for reference implementation of OnElementChanged.

   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.SetNativeControl(TNativeElement control)
   at Lottie.Forms.UWP.Renderers.AnimationViewRenderer.<OnElementChanged>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()

![c1119565-914c-4569-beb4-92d7b1c35e2f](https://user-images.githubusercontent.com/9450530/37493427-dd37bd76-2872-11e8-93ec-6caf1f6dee48.GIF)

Reproduction Link: https://drive.google.com/open?id=10B2Qhbe4MPyBaOBzn4emdCYmWSDgltBh

**Comment by azchohfi** [comment]
This is a bug in Lottie.Xamarin. Fix is here:
https://github.com/martijn00/LottieXamarin/pull/152

**Comment by azchohfi** [comment]
Fixed on the other repo.
